// <auto-generated />
using MUDhub.Prototype.Server.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MUDhub.Prototype.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200323161652_AddRooms")]
    partial class AddRooms
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("MUDhub.Prototype.Server.Models.Point", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Uid");

                    b.ToTable("Point");
                });

            modelBuilder.Entity("MUDhub.Prototype.Server.Models.Room", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EastId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnterMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NorthId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SouthId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WestId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PositionUid");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("MUDhub.Prototype.Server.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MUDhub.Prototype.Server.Models.Room", b =>
                {
                    b.HasOne("MUDhub.Prototype.Server.Models.Point", "Position")
                        .WithMany()
                        .HasForeignKey("PositionUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
